import type { Metadata } from "next";
import Link from "next/link";
import AiMoneyChat from "@/components/AiMoneyChat";
import { IconSparkle } from "@/components/icons";
import { site } from "@/lib/site";

const OG_TITLE = "Free AI Money Assistant - Ask Any Finance Question";
const OG_DESC =
  "Ask CoinMind's free AI assistant about investing, taxes, budgeting, SIPs, mutual funds and AI tools. Instant answers, no sign-up. Educational information, not financial advice.";

export const metadata: Metadata = {
  title: { absolute: "Free AI Money Assistant - Ask Anything" },
  description:
    "A free AI assistant for money and AI questions: investing, taxes, budgeting, saving and choosing AI tools. Instant answers, no sign-up.",
  alternates: { canonical: "/ai-assistant" },
  openGraph: {
    title: OG_TITLE,
    description: OG_DESC,
    url: "/ai-assistant",
    type: "website",
    siteName: site.name,
    locale: "en_IN",
    images: [{ url: "/opengraph-image", width: 1200, height: 630, alt: OG_TITLE }],
  },
  twitter: {
    card: "summary_large_image",
    title: OG_TITLE,
    description: OG_DESC,
    images: ["/opengraph-image"],
  },
};

const CAN_DO = [
  "Explain SIP, mutual funds, FD, PPF and other investments in simple terms",
  "Compare the new vs old income tax regime for your situation",
  "Help you budget, save more and build an emergency fund",
  "Suggest which AI tool fits a task, and how to use it well",
  "Break down financial jargon into plain English",
  "Point you to the right free CoinMind calculator",
];

const FAQS: { q: string; a: string }[] = [
  {
    q: "What can the CoinMind AI assistant do?",
    a: "It answers general questions about personal finance and AI tools: how a SIP or an EMI works, what the difference between the new and old income tax regimes is, how to start an emergency fund, what a term in your statement means, or which AI tool suits a task. It writes in plain English and points you to the relevant free CoinMind calculator when there is one.",
  },
  {
    q: "What can it not do?",
    a: "It cannot give you personalised financial advice, recommend a specific mutual fund, stock, insurance policy or loan product, or tell you what to buy. It has no access to your bank accounts, portfolio, PAN or any CoinMind calculator inputs. It is also not a live data feed: it is instructed not to invent exact rates, slabs or legal provisions it is unsure of, so always confirm current figures against an official source before you act on them.",
  },
  {
    q: "Is this financial advice?",
    a: "No. Everything the assistant produces is general educational information. CoinMind is not a SEBI-registered investment adviser, broker or tax consultant, and no answer here is a recommendation to buy, sell or hold anything. For a decision that materially affects your money, speak to a qualified, licensed professional who can consider your personal circumstances. See our full disclaimer for details.",
  },
  {
    q: "Are my conversations stored?",
    a: "No. CoinMind does not save your chat. The conversation lives only in your browser tab while the page is open and disappears when you refresh or close it. There is no account, so nothing is tied to an identity. To keep the thread coherent, the most recent messages of the current conversation are sent along with your new question to the AI provider that generates the reply, and that provider's own privacy policy applies to that request.",
  },
  {
    q: "Which AI model powers the assistant?",
    a: "The reply is generated by whichever provider is configured on the server, tried in order: DeepSeek (deepseek-chat) first, then Groq running Llama 3.3 70B or Llama 3.1 8B, then Google Gemini Flash as a final fallback. The API keys stay server-side and your browser never sees them. Because the fallback order can change with availability, treat every answer as a starting point to verify rather than a source of record.",
  },
  {
    q: "How much does it cost?",
    a: "Nothing. The assistant is free and unmetered for readers, with no trial, no credit card and no paywall. CoinMind is funded by advertising and occasional affiliate links, which are explained in full on our affiliate disclosure page.",
  },
  {
    q: "Do I need to create an account or sign in?",
    a: "No. There is no sign-up, no email capture and no login anywhere on CoinMind. Open the page and start typing.",
  },
  {
    q: "Can it tell me today's interest rates or tax slabs?",
    a: "Not reliably. The assistant works from what its underlying model has learned, not from a live feed of RBI, bank or Income Tax Department data, and it is explicitly instructed to avoid stating exact numbers it is unsure about. Use it to understand how something is calculated, then check the current figure with the official source and run the numbers in the relevant CoinMind calculator.",
  },
  {
    q: "Can it replace a chartered accountant or a SEBI-registered adviser?",
    a: "No, and it is not meant to. It is a faster way to understand your options and to arrive at a sharper question. Filing decisions, portfolio construction, insurance and anything with a legal or tax consequence should go to a licensed professional.",
  },
  {
    q: "What should I do if an answer looks wrong?",
    a: "Trust the official source over the assistant, and please tell us. Email " + site.email + " and we will check it. Genuine errors in our own content are logged publicly with a date on our corrections page.",
  },
];

export default function Page() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebApplication",
        name: "CoinMind AI Money Assistant",
        url: `${site.url}/ai-assistant`,
        description:
          "A free AI assistant that answers general questions about personal finance, investing, taxes, budgeting and AI tools in plain English. Educational information only, not financial advice.",
        applicationCategory: "FinanceApplication",
        operatingSystem: "All",
        browserRequirements: "Requires JavaScript",
        isAccessibleForFree: true,
        offers: { "@type": "Offer", price: "0", priceCurrency: "INR" },
        featureList: CAN_DO,
        publisher: { "@type": "Organization", name: site.name, url: site.url },
      },
      {
        "@type": "FAQPage",
        mainEntity: FAQS.map((f) => ({
          "@type": "Question",
          name: f.q,
          acceptedAnswer: { "@type": "Answer", text: f.a },
        })),
      },
    ],
  };

  return (
    <div className="mx-auto max-w-3xl px-4 sm:px-6 pb-10">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <header className="pt-14 pb-6 text-center">
        <span className="inline-flex items-center gap-2 rounded-full bg-forest-soft px-3 py-1.5 text-xs font-semibold text-forest">
          <IconSparkle className="h-3.5 w-3.5" /> Free AI Assistant
        </span>
        <h1 className="mt-4 font-display text-4xl sm:text-5xl font-600 text-ink leading-[1.05]">
          Your free AI money assistant
        </h1>
        <p className="mt-4 text-lg text-ink-soft leading-relaxed max-w-xl mx-auto">
          Ask anything about investing, taxes, saving, budgeting or AI tools,
          and get a clear, instant answer. No sign-up, no cost.
        </p>
        <p className="mt-3 text-sm text-ink-faint leading-relaxed max-w-xl mx-auto">
          This assistant gives general educational information. It is not
          personalised financial advice, and {site.name} is not a
          SEBI-registered investment adviser.
        </p>
      </header>

      <AiMoneyChat />

      <section className="mt-14 max-w-3xl mx-auto">
        <h2 className="font-display text-2xl font-600 text-ink">
          What can it help with?
        </h2>
        <div className="mt-4 grid sm:grid-cols-2 gap-3 text-sm text-ink-soft">
          {CAN_DO.map((t) => (
            <div key={t} className="rounded-xl border border-line bg-card p-4">
              {t}
            </div>
          ))}
        </div>
        <p className="mt-6 text-sm text-ink-faint leading-relaxed">
          This assistant gives general, educational information, not personalised
          financial advice. Always verify figures and, for major decisions,
          consider a qualified professional. Read our full{" "}
          <Link href="/disclaimer" className="text-forest underline underline-offset-2">disclaimer</Link>.
        </p>
      </section>

      <section className="mt-14 max-w-3xl mx-auto">
        <h2 className="font-display text-2xl font-600 text-ink">
          Questions people ask about this assistant
        </h2>
        <div className="mt-5 space-y-4">
          {FAQS.map((f) => (
            <div key={f.q} className="rounded-xl border border-line bg-card p-5">
              <h3 className="text-base font-600 text-ink">{f.q}</h3>
              <p className="mt-2 text-sm text-ink-soft leading-relaxed">{f.a}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-12 max-w-3xl mx-auto rounded-2xl border border-line bg-paper-2 p-6 text-sm text-ink-soft">
        <h2 className="font-display text-lg font-600 text-ink">
          Prefer to run the numbers yourself?
        </h2>
        <p className="mt-2 leading-relaxed">
          The assistant explains concepts; our{" "}
          <Link href="/calculators" className="text-forest underline underline-offset-2">free calculators</Link>{" "}
          do the maths, privately in your browser. Every formula and source is
          documented on our{" "}
          <Link href="/methodology" className="text-forest underline underline-offset-2">methodology</Link>{" "}
          page, and our wider process is set out in our{" "}
          <Link href="/editorial-standards" className="text-forest underline underline-offset-2">editorial standards</Link>.
        </p>
      </section>
    </div>
  );
}
