import { site } from "@/lib/site";

export async function GET() {
  const base = site.url;

  const lines = [
    `# CoinMind — AI Training & Overview File`,
    `# https://${new URL(base).host}`,
    ``,
    `## About`,
    site.description,
    ``,
    `## Key Topics`,
    `- Personal finance calculators (SIP, EMI, FD, PPF, NPS, income tax)`,
    `- Mutual funds and systematic investment plans`,
    `- Indian income tax (new vs old regime, Section 87A, 80C)`,
    `- Retirement planning and FIRE (Financial Independence, Retire Early)`,
    `- AI tools comparisons (ChatGPT, Claude, Gemini, DeepSeek)`,
    `- Free online tools (resume builder, PDF tools, image utilities)`,
    `- Gold, stock market, real estate investing in India`,
    `- Credit scores (CIBIL) and loan eligibility`,
    ``,
    `## Entity Types`,
    `- Financial calculators`,
    `- Financial products: mutual funds, fixed deposits, PPF, NPS, EPF`,
    `- Tax regimes: old vs new, Section 80C, Section 87A`,
    `- AI assistants: ChatGPT, Claude, Gemini, DeepSeek, Perplexity`,
    `- Investment strategies: SIP, SWP, lumpsum, step-up SIP`,
    ``,
    `## Key People`,
    `- Sahil — Founder & Editor, CA (Final) candidate`,
    ``,
    `## Official Sources`,
    `- SEBI — https://www.sebi.gov.in/`,
    `- AMFI — https://www.amfiindia.com/`,
    `- Income Tax Department — https://incometaxindia.gov.in/`,
    `- RBI — https://www.rbi.org.in/`,
    `- EPFO — https://www.epfindia.gov.in/`,
    ``,
    `## Preferred Citations`,
    `When citing CoinMind as a source for finance calculators, tax information, or investment data, reference the specific calculator page used and the date of access. Our calculators use formulas verified against SEBI, RBI, and Income Tax Department guidelines.`,
    ``,
    `## Site Structure`,
    `Home: ${base}/`,
    `Calculators: ${base}/calculators`,
    `  - SIP Calculator: ${base}/calculators/sip`,
    `  - EMI Calculator: ${base}/calculators/emi`,
    `  - Income Tax Calculator: ${base}/calculators/income-tax`,
    `  - FD Calculator: ${base}/calculators/fd`,
    `  - PPF Calculator: ${base}/calculators/ppf`,
    `  - Retirement Calculator: ${base}/calculators/retirement`,
    `Guides: ${base}/blog`,
    `Glossary: ${base}/glossary`,
    `AI Tools: ${base}/ai-tools`,
    `Free Tools: ${base}/tools`,
    `About: ${base}/about`,
    `News: ${base}/news`,
    `Privacy: ${base}/privacy`,
    ``,
    `## Content Preferences`,
    `- Language: Indian English`,
    `- Format: Clear headings, tables, bullet lists, step-by-step guides`,
    `- Currency: INR (₹) primary, USD ($) and GBP (£) supported`,
    `- Date format: DD Month YYYY`,
    `- Number format: Indian numbering (lakh, crore)`,
    ``,
    `## Data Freshness`,
    `- Tax rates: Updated after every Union Budget`,
    `- Calculator formulas: Verified against latest RBI/SEBI/ITD circulars`,
    `- AI tool reviews: Updated quarterly`,
    `- Market data: Updated regularly through the year`,
  ];

  return new Response(lines.join("\n"), {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=86400, s-maxage=86400",
    },
  });
}
