import type { Metadata } from "next";
import HubPage from "@/components/HubPage";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: { absolute: "SIP Investment Guide - Systematic Investment Plans Explained" },
  description: "Complete SIP guide: calculator, step-up SIP, goal SIP, SWP, and tax on mutual fund SIPs. Learn how SIP works, how much to invest, and which strategy fits your goal.",
  alternates: { canonical: `${site.url}/sip` },
};

export default function Page() {
  return (
    <HubPage
      title="SIP & Systematic Investment Plans"
      description="Everything you need to know about SIP investing in India. Calculate returns, compare strategies, understand taxation, and find the right SIP for your financial goals."
      badge="SIP Hub"
      sections={[
        {
          title: "SIP Calculators",
          columns: 3,
          links: [
            { title: "SIP Calculator", href: "/calculators/sip", desc: "Calculate monthly SIP returns with step-up and LTCG tax impact" },
            { title: "Goal SIP Calculator", href: "/calculators/goal-sip", desc: "Find the exact SIP needed for ₹1 crore or any financial goal" },
            { title: "Step-Up SIP Calculator", href: "/calculators/step-up-sip", desc: "Compare flat vs step-up SIP returns side-by-side" },
            { title: "Lumpsum Calculator", href: "/calculators/lumpsum", desc: "Project one-time investment growth with CAGR" },
            { title: "SWP Calculator", href: "/calculators/swp", desc: "Plan monthly withdrawals from your mutual fund corpus" },
            { title: "Mutual Fund Returns Calculator", href: "/calculators/mutual-fund-returns", desc: "Project lumpsum MF returns with CAGR" },
          ],
        },
        {
          title: "SIP Guides & Strategies",
          columns: 2,
          links: [
            { title: "SIP vs Lumpsum: Which is Better?", href: "/blog/sip-vs-lumpsum", desc: "The real math comparing SIP and lump sum investing for different market conditions" },
            { title: "How Much SIP for ₹1 Crore?", href: "/blog/sip-to-become-crorepati", desc: "The exact monthly SIP amount needed to reach ₹1 crore at different time horizons" },
            { title: "Mutual Funds for Beginners", href: "/blog/mutual-funds-beginners-india", desc: "Step-by-step guide to starting your first SIP in India" },
            { title: "How to Start Investing in India", href: "/blog/how-to-start-investing-in-india", desc: "KYC, picking a fund, and setting up your first monthly SIP" },
            { title: "Capital Gains Tax on Mutual Funds", href: "/blog/capital-gains-tax-mutual-funds-shares", desc: "How SIP gains are taxed: LTCG, STCG, and what you actually owe" },
          ],
        },
        {
          // Slugs are generated by lib/pseo-sip.ts (amount axis) and
          // lib/pseo-sip-years.ts (amount × duration). Both now live under
          // /sip/[slug]; only amounts present in SIP_AMOUNTS resolve.
          title: "SIP by Amount",
          columns: 4,
          links: [
            { title: "₹1,000 SIP Monthly", href: "/sip/1000-per-month", desc: "Returns from ₹1,000 monthly SIP" },
            { title: "₹2,000 SIP Monthly", href: "/sip/2000-per-month", desc: "Returns from ₹2,000 monthly SIP" },
            { title: "₹3,000 SIP Monthly", href: "/sip/3000-per-month", desc: "Returns from ₹3,000 monthly SIP" },
            { title: "₹5,000 SIP Monthly", href: "/sip/5000-per-month", desc: "Returns from ₹5,000 monthly SIP" },
            { title: "₹7,000 SIP Monthly", href: "/sip/7000-per-month", desc: "Returns from ₹7,000 monthly SIP" },
            { title: "₹10,000 SIP Monthly", href: "/sip/10000-per-month", desc: "Returns from ₹10,000 monthly SIP" },
            { title: "₹15,000 SIP Monthly", href: "/sip/15000-per-month", desc: "Returns from ₹15,000 monthly SIP" },
            { title: "₹20,000 SIP Monthly", href: "/sip/20000-per-month", desc: "Returns from ₹20,000 monthly SIP" },
            { title: "₹25,000 SIP Monthly", href: "/sip/25000-per-month", desc: "Returns from ₹25,000 monthly SIP" },
            { title: "₹50,000 SIP Monthly", href: "/sip/50000-per-month", desc: "Returns from ₹50,000 monthly SIP" },
          ],
        },
        {
          title: "SIP by Duration",
          columns: 3,
          links: [
            { title: "₹5,000 SIP for 3 Years", href: "/sip/5000-per-month-for-3-years", desc: "SIP returns over a 3 year horizon" },
            { title: "₹5,000 SIP for 5 Years", href: "/sip/5000-per-month-for-5-years", desc: "SIP returns over a 5 year horizon" },
            { title: "₹5,000 SIP for 10 Years", href: "/sip/5000-per-month-for-10-years", desc: "SIP returns over a 10 year horizon" },
            { title: "₹5,000 SIP for 15 Years", href: "/sip/5000-per-month-for-15-years", desc: "SIP returns over a 15 year horizon" },
            { title: "₹5,000 SIP for 20 Years", href: "/sip/5000-per-month-for-20-years", desc: "SIP returns over a 20 year horizon" },
            { title: "₹5,000 SIP for 25 Years", href: "/sip/5000-per-month-for-25-years", desc: "SIP returns over a 25 year horizon" },
          ],
        },
        {
          title: "Related Calculators",
          columns: 3,
          links: [
            { title: "CAGR Calculator", href: "/calculators/cagr", desc: "Calculate compound annual growth rate" },
            { title: "Compound Interest Calculator", href: "/calculators/compound-interest", desc: "See compounding across daily/monthly/yearly periods" },
            { title: "Retirement Calculator", href: "/calculators/retirement", desc: "Find the corpus and monthly SIP needed for retirement" },
            { title: "FD Calculator", href: "/calculators/fd", desc: "Compare FD returns against SIP" },
            { title: "PPF Calculator", href: "/calculators/ppf", desc: "PPF vs SIP return comparison" },
            { title: "NPS Calculator", href: "/calculators/nps", desc: "NPS vs SIP for retirement" },
          ],
        },
        {
          title: "Key Glossary Terms",
          columns: 4,
          links: [
            { title: "SIP Definition", href: "/glossary/sip", desc: "What is a Systematic Investment Plan" },
            { title: "Mutual Fund", href: "/glossary/mutual-fund", desc: "How mutual funds work" },
            { title: "NAV", href: "/glossary/nav", desc: "Net Asset Value explained" },
            { title: "Rupee Cost Averaging", href: "/glossary/rupee-cost-averaging", desc: "How SIP reduces market timing risk" },
            { title: "CAGR", href: "/glossary/cagr", desc: "Compound Annual Growth Rate" },
            { title: "Expense Ratio", href: "/glossary/expense-ratio", desc: "What mutual funds charge you" },
            { title: "ELSS", href: "/glossary/elss", desc: "Tax-saving mutual funds" },
            { title: "LTCG Tax", href: "/glossary/capital-gains", desc: "Long-term capital gains tax on mutual funds" },
          ],
        },
      ]}
      relatedHubs={[
        { title: "Investing", href: "/investing" },
        { title: "Savings", href: "/savings" },
        { title: "Retirement", href: "/retirement" },
        { title: "Tax", href: "/income-tax" },
      ]}
    />
  );
}
